# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: دلنوشته‌های یک برنامه نویس
email: s.m.hadi.naghavi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 دلنوشته‌های یک برنامه نویس
github_username: smhnaghavi
minimal_mistakes_skin: air
search: true
og_image: https://smhnaghavi.github.io/blog/assets/images/favicon.png
logo: https://smhnaghavi.github.io/blog/assets/images/favicon.png

locale: "fa-IR"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: IR

lang: fa
dir: rtl
direction: rtl

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://smhnaghavi.github.io/blog

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#comments:
#   provider: "giscus"

repository: "smhnaghavi/blog"

comments:
  provider: ""
  giscus:
#     repo_id              : "MDEwOlJlcG9zaXRvcnkzMjE5OTM3NDM="
    category_name        : "General"
    category_id          : "DIC_kwDOEzE8D84B-PIL"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "dark"
    crossorigin          : "anonymous"

#utterances:
#  repo: "MHKarami97/blog"
#  issue-term: "pathname"
#  label: "Comments"
#  theme: "github-light"



# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: "G-DZM25ZLKRP"
# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "G-DZM25ZLKRP"
#     anonymize_ip: false # default

# google_site_verification: "BVwx9je8Sv6HbUTtZ4yJrPvJLZzE0wEsPS2VJHQzOKo"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "سیدمحمدهادی نقوی"
  avatar : "https://smhnaghavi.github.io/blog/assets/images/favicon.png"
  bio    : "دلنوشته‌های یک برنامه نویس"
  links:
    - label: "وبسایت"
      icon: "fas fa-fw fa-link"
      url: "https://smhnaghavi.github.io"
    - label: "گیت هاب"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/smhnaghavi"
    - label: "ایمیل "
      icon: "fab fa fa-envelope"
      url: "mailto:s.m.hadi.naghavi@gmail.com"

footer:
  links:
    - label: "Email"
      icon: "fab fa-fw fa-email"
      url: "s.m.hadi.naghavi@gmail.com"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/smhnaghavi"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      lang: fa
      direction: rtl
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: fa
      direction: rtl

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Style codes in mark down
markdown: redcarpet
extensions: [fenced_code_blocks]
